# Generated by Django 4.2.11 on 2025-05-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_favorite_recipe_alter_favorite_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
