# Generated by Django 4.2.11 on 2025-05-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_delete_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "default_related_name": "favorited",
                "verbose_name": "избранный рецепт",
                "verbose_name_plural": "избранные рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "in_carts",
                "verbose_name": "рецепт в списке покупок",
                "verbose_name_plural": "списки покупок",
            },
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"),
                name="unique_recipe_ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_shopping_cart"
            ),
        ),
    ]
