# Generated by Django 4.2.11 on 2025-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0003_subscription_subscription_unique_subscription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
    ]
