name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: foodgram
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install dj-database-url

      - name: Run migrations and tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/foodgram
        run: |
          cd backend
          python manage.py migrate
          python manage.py test

      - name: Install Node.js (для newman)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run Postman tests
        run: |
          newman run postman_collection/foodgram.postman_collection.json \
            --env-var "baseUrl=http://localhost:8000" \
            --env-var "email=testuser@example.com" \
            --env-var "username=testuser" \
            --env-var "password=strongpassword123" \
            --env-var "secondUserEmail=second@example.com" \
            --env-var "secondUserUsername=seconduser" \
            --env-var "thirdUserEmail=third@example.com" \
            --env-var "thirdUserUsername=thirduser"