name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  REGISTRY: docker.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          pip install -r backend/requirements.txt

      - name: Run linters
        run: |
          black --check backend
          isort --check-only backend
          flake8 backend

  build-and-push:
    needs: lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/foodgram-back:latest
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/foodgram-back:${{ github.sha }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/foodgram-front:latest
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/foodgram-front:${{ github.sha }}
